/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reconinstruments_reconsensor_SensorNative */

#ifndef _Included_com_reconinstruments_reconsensor_SensorNative
#define _Included_com_reconinstruments_reconsensor_SensorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reconinstruments_reconsensor_SensorNative
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_reconinstruments_reconsensor_SensorNative_openDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_reconinstruments_reconsensor_SensorNative
 * Method:    closeDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_reconinstruments_reconsensor_SensorNative_closeDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_reconinstruments_reconsensor_SensorNative
 * Method:    getSensorStatus
 * Signature: (IILcom/reconinstruments/reconsensor/SensorStatus;)I
 */
JNIEXPORT jint JNICALL Java_com_reconinstruments_reconsensor_SensorNative_getSensorStatus
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_reconinstruments_reconsensor_SensorNative
 * Method:    setReportingMode
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_reconinstruments_reconsensor_SensorNative_setReportingMode
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_reconinstruments_reconsensor_SensorNative
 * Method:    startQueue
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_reconinstruments_reconsensor_SensorNative_startQueue
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_reconinstruments_reconsensor_SensorNative
 * Method:    stopQueue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_reconinstruments_reconsensor_SensorNative_stopQueue
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
